/**
 * Pre-generated exercise bank seeder (2026-09-14).
 *
 * Why: first-time exercise generation took 6-14s — the biggest remaining
 * wait in the product. This fills lib/exercises/store.ts's shared
 * exercise table ahead of time, so a kid's real session almost always
 * hits findReusableExercise() (instant) instead of generateExercise()
 * (an LLM call on the critical path).
 *
 * This is NOT a separate storage system: the bank IS the `exercises`
 * table exercise generation has always written to (lib/exercises/
 * store.ts's own header: "every exercise that's generated should be
 * logged and reused"). Seeding just pre-pays that cost in bulk, offline,
 * instead of once per kid per topic the first time they show up.
 *
 * Guard compatibility (non-negotiable, per the brief): every exercise
 * this script accepts passes lib/exercises/bank-guard.ts's
 * verifyExercise() — the SAME structured-spec check the live arithmetic
 * guard uses, extended here to every bankable subtype. explain_thinking
 * and shape_match have no structured spec by design (see bank-guard.ts's
 * header) and are never generated by this script.
 *
 * Idempotent top-up: for each of the 35 topics x 3 levels, this checks
 * the CURRENT count of guard-passing, fingerprint-distinct exercises
 * already banked and only generates the shortfall to reach TARGET_PER_SLOT
 * — re-running costs nothing once a slot is full, and a partially-drained
 * slot (rows deleted, or the target raised) tops back up to exactly the
 * target, never past it.
 *
 * Run: npx tsx scripts/seed-exercise-bank.ts [--out <path>] [--existing <path>]
 *      [--target <n>] [--concurrency <n>] [--topics id1,id2,...] [--levels 1,2,3]
 *
 * Persistence, two modes:
 * - SUPABASE_SERVICE_ROLE_KEY set: reads the current bank and inserts new
 *   rows directly — the intended, fully autonomous mode for a real
 *   scheduled run (this app has never needed a service-role key before;
 *   every existing write goes through a signed-in parent's own RLS-scoped
 *   session, which a standalone maintenance script has no user session
 *   to borrow). This is the mode to configure for production top-up.
 * - Not set: generates and verifies exactly the same way, but reads
 *   "what's already banked" from --existing (a JSON snapshot; empty if
 *   omitted) and WRITES THE RESULT TO --out instead of the database —
 *   for an operator with direct DB access to apply. Used for this
 *   session's actual seeding run; documented rather than hidden.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { TOPICS, type MapTopic } from "../lib/map/topics";
import { generateExercise } from "../lib/exercises/generate";
import { verifyExercise, specFingerprint, isBankableSubtype } from "../lib/exercises/bank-guard";
import type { Exercise, ExerciseSubtype } from "../lib/exercises/types";
import type { Database } from "../lib/supabase/database.types";

// ---- env (same manual-load trick used elsewhere this session — this
// script runs via plain tsx, outside Next's own env loading). Optional:
// CI (the top-up GitHub Actions workflow) injects env vars directly and
// has no .env.local checked out — only load it when present, never
// override a var CI already set. ----------
const envLocalPath = new URL("../.env.local", import.meta.url);
if (existsSync(envLocalPath)) {
  for (const line of readFileSync(envLocalPath, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "").trim();
  }
}

// ---- CLI args -----------------------------------------------------------
function arg(name: string, def?: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : def;
}
const OUT_PATH = arg("out", "/tmp/bank-seed-output.json")!;
const EXISTING_PATH = arg("existing");
const TARGET_PER_SLOT = Number(arg("target", "10"));
const CONCURRENCY = Number(arg("concurrency", "8"));
const TOPIC_FILTER = arg("topics")?.split(",");
const LEVEL_FILTER = arg("levels")?.split(",").map(Number);

// Ordered by how topic-agnostic each subtype's guard is, not alphabetically
// or by "tier": pick_operation (any word problem, just needs 4 distinct
// choices) and visual_grouping (any countable-items scenario) pass the
// guard for nearly any topic's content. fill_in_blank/pattern_completion/
// equation_balance need the topic's own content to already BE a bare
// numeric expression or sequence — true for "numbers"/"addition" topics,
// false for "geometry"/"time"/"length" ones, where the model has no
// {operands,operators} to extract and burns its whole retry budget
// failing the same way repeatedly (observed directly: math-a-geometry
// with the old fill_in_blank-first order spent 20+ min and 100+ LLM calls
// on ONE level-1 slot without a single acceptance). Leading with the
// robust subtypes means every topic banks SOMETHING quickly even when the
// pickier subtypes never fit it.
const MATH_BANKABLE: ExerciseSubtype[] = ["pick_operation", "visual_grouping", "number_line_placement", "fill_in_blank", "pattern_completion", "equation_balance"];
const HEBREW_BANKABLE: ExerciseSubtype[] = ["comprehension", "spelling_correction_mc", "root_pattern_mc", "word_build", "sentence_order", "vowel_select_mc", "phonemic_visual_mc"];
for (const s of [...MATH_BANKABLE, ...HEBREW_BANKABLE]) {
  if (!isBankableSubtype(s)) throw new Error(`${s} is listed as bankable but bank-guard.ts disagrees — fix the mismatch before running.`);
}

interface SlotState {
  topicId: string;
  difficulty: 1 | 2 | 3;
  count: number;
  fingerprints: Set<string>;
}
type ExistingSnapshot = Record<string, { count: number; fingerprints: string[] }>;

const slotKey = (topicId: string, difficulty: number) => `${topicId}:${difficulty}`;

async function loadExisting(supabase: SupabaseClient<Database> | null): Promise<Map<string, SlotState>> {
  const slots = new Map<string, SlotState>();
  for (const topic of TOPICS) {
    for (const difficulty of [1, 2, 3] as const) {
      slots.set(slotKey(topic.id, difficulty), { topicId: topic.id, difficulty, count: 0, fingerprints: new Set() });
    }
  }

  if (supabase) {
    const { data, error } = await supabase.from("exercises").select("*").not("topic_id", "is", null);
    if (error) throw new Error(`Failed to read existing bank: ${error.message}`);
    for (const row of data ?? []) {
      const difficulty = row.difficulty;
      if (!row.topic_id || (difficulty !== 1 && difficulty !== 2 && difficulty !== 3)) continue;
      const ex = rowToExerciseForVerify(row);
      const result = verifyExercise(ex);
      if (!result.ok) continue; // an ungated row already there doesn't count toward the target
      const slot = slots.get(slotKey(row.topic_id, difficulty));
      if (!slot) continue;
      slot.count++;
      slot.fingerprints.add(specFingerprint(ex));
    }
  } else if (EXISTING_PATH && existsSync(EXISTING_PATH)) {
    const snapshot: ExistingSnapshot = JSON.parse(readFileSync(EXISTING_PATH, "utf8"));
    for (const [key, v] of Object.entries(snapshot)) {
      const slot = slots.get(key);
      if (slot) {
        slot.count = v.count;
        v.fingerprints.forEach((f) => slot.fingerprints.add(f));
      }
    }
  }
  return slots;
}

// Minimal shape needed to run verifyExercise/specFingerprint over an
// already-banked row without pulling in lib/exercises/store.ts's whole
// rowToExercise (which needs the live parseComputation re-validation path
// this script doesn't otherwise touch).
function rowToExerciseForVerify(row: Record<string, unknown>): Exercise {
  return {
    id: row.id as string,
    subject: row.subject as "math" | "hebrew",
    grade: row.grade as "א" | "ב" | "ג",
    type: row.type as Exercise["type"],
    subtype: (row.subtype as ExerciseSubtype) ?? undefined,
    topic: row.topic as string,
    topicId: (row.topic_id as string) ?? undefined,
    passage: (row.passage as string) ?? undefined,
    question: row.question as string,
    choices: (row.choices as string[]) ?? undefined,
    numberLine: (row.number_line as Exercise["numberLine"]) ?? undefined,
    tiles: (row.tiles as Exercise["tiles"]) ?? undefined,
    grouping: (row.grouping as Exercise["grouping"]) ?? undefined,
    correctAnswer: row.correct_answer as string,
    computation: (row.computation as Exercise["computation"]) ?? undefined,
    difficulty: (row.difficulty as 1 | 2 | 3) ?? undefined,
  };
}

/** A handful of common kid names to steer away from, batch to batch, so
 *  "no template smell" (the brief's own words) means something concrete —
 *  varietyHint tells the model which ones are already used in THIS slot. */
const NAME_POOL = ["דני", "שרה", "רונה", "יונתן", "מאיה", "עומר", "נועה", "איתי", "תמר", "אלון", "שירה", "גיא"];

async function generateOneForSlot(topic: MapTopic, difficulty: 1 | 2 | 3, subtype: ExerciseSubtype, usedNames: string[]): Promise<Exercise | null> {
  const varietyHint = usedNames.length > 0
    ? `גיוון: אל תשתמשו שוב בשמות ${usedNames.slice(-4).join(", ")} — בחרו שם/תרחיש אחר לגמרי מהתרגילים הקודמים בסבב הזה.`
    : undefined;
  const MAX_ATTEMPTS = 3;
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      const ex = await generateExercise({
        subject: topic.subject,
        grade: topic.grade,
        profile: null,
        topicId: topic.id,
        level: difficulty,
        forceSubtype: subtype,
        varietyHint,
      });
      const result = verifyExercise(ex);
      if (!result.ok) {
        console.warn(`[seed] ${topic.id} L${difficulty} ${subtype} attempt ${attempt}: guard rejected — ${result.reason}`);
        continue;
      }
      return ex;
    } catch (err) {
      console.warn(`[seed] ${topic.id} L${difficulty} ${subtype} attempt ${attempt}: ${err instanceof Error ? err.message : err}`);
    }
  }
  return null;
}

function nameIn(ex: Exercise): string | null {
  return NAME_POOL.find((n) => ex.question.includes(n)) ?? null;
}

async function fillSlot(topic: MapTopic, difficulty: 1 | 2 | 3, slot: SlotState): Promise<Exercise[]> {
  const pool = topic.subject === "math" ? MATH_BANKABLE : HEBREW_BANKABLE;
  const need = Math.max(0, TARGET_PER_SLOT - slot.count);
  if (need === 0) return [];
  const accepted: Exercise[] = [];
  const usedNames: string[] = [];
  let subtypeIndex = 0;
  let consecutiveDupes = 0;
  // Bounded to one full cycle of the pool (was 2x — with MAX_ATTEMPTS=3
  // internal retries each, one full cycle is already up to pool.length*3*3
  // LLM calls for a slot that fits NO subtype at all; doubling that just
  // burns time restating the same failure, it doesn't change the outcome).
  while (accepted.length < need && consecutiveDupes < pool.length) {
    const subtype = pool[subtypeIndex % pool.length];
    subtypeIndex++;
    const ex = await generateOneForSlot(topic, difficulty, subtype, usedNames);
    if (!ex) {
      consecutiveDupes++; // generation itself failed every retry — treat like a dupe for the give-up counter
      continue;
    }
    const fp = specFingerprint(ex);
    if (slot.fingerprints.has(fp)) {
      console.warn(`[seed] ${topic.id} L${difficulty} ${subtype}: duplicate spec, discarding and retrying`);
      consecutiveDupes++;
      continue;
    }
    consecutiveDupes = 0;
    slot.fingerprints.add(fp);
    const name = nameIn(ex);
    if (name) usedNames.push(name);
    accepted.push(ex);
  }
  if (accepted.length < need) {
    console.warn(`[seed] ${topic.id} L${difficulty}: only reached ${slot.count + accepted.length}/${TARGET_PER_SLOT} after repeated rejections`);
  }
  return accepted;
}

async function mapWithConcurrency<T, R>(items: T[], limit: number, fn: (item: T, index: number) => Promise<R>): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  async function worker() {
    while (true) {
      const i = next++;
      if (i >= items.length) return;
      results[i] = await fn(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return results;
}

async function main() {
  const hasServiceKey = !!process.env.SUPABASE_SERVICE_ROLE_KEY;
  const supabase = hasServiceKey
    ? createClient<Database>(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!)
    : null;
  console.log(
    hasServiceKey
      ? "[seed] SUPABASE_SERVICE_ROLE_KEY found — reading/writing the database directly."
      : `[seed] No SUPABASE_SERVICE_ROLE_KEY — generate-and-verify only; reading existing state from ${EXISTING_PATH ?? "(none — treating the bank as empty)"}, writing accepted exercises to ${OUT_PATH} for external insertion.`
  );

  const slots = await loadExisting(supabase);
  const topics = TOPIC_FILTER ? TOPICS.filter((t) => TOPIC_FILTER.includes(t.id)) : TOPICS;
  const levels = (LEVEL_FILTER ?? [1, 2, 3]) as (1 | 2 | 3)[];

  const work: { topic: MapTopic; difficulty: 1 | 2 | 3 }[] = [];
  for (const topic of topics) for (const difficulty of levels) work.push({ topic, difficulty });

  console.log(`[seed] ${work.length} slots (${topics.length} topics x ${levels.length} levels), target ${TARGET_PER_SLOT}/slot, concurrency ${CONCURRENCY}.`);

  const allNew: Exercise[] = [];
  const perSlotResult: { topicId: string; difficulty: number; before: number; added: number; after: number }[] = [];

  await mapWithConcurrency(work, CONCURRENCY, async ({ topic, difficulty }) => {
    const slot = slots.get(slotKey(topic.id, difficulty))!;
    const before = slot.count;
    const added = await fillSlot(topic, difficulty, slot);
    allNew.push(...added);
    perSlotResult.push({ topicId: topic.id, difficulty, before, added: added.length, after: before + added.length });
    console.log(`[seed] ${topic.id} L${difficulty}: ${before} -> ${before + added.length}`);
    // Checkpoint after every slot, not just at the very end: a run over
    // ~100 slots takes long enough that losing everything to an
    // interruption (or this session simply running out of time) would
    // throw away real, already-verified work. Safe to do — only THIS
    // process writes allNew, and JSON.stringify of a plain array is cheap
    // even at bank scale (~1000 exercises).
    if (!supabase) writeFileSync(OUT_PATH, JSON.stringify(allNew, null, 1));
  });

  if (supabase) {
    const rows = allNew.map((ex) => ({
      subject: ex.subject,
      grade: ex.grade,
      type: ex.type,
      subtype: ex.subtype ?? null,
      topic: ex.topic,
      topic_id: ex.topicId ?? null,
      passage: ex.passage ?? null,
      question: ex.question,
      choices: ex.choices ?? null,
      // Casts mirror lib/exercises/store.ts's saveExercise: these are
      // plain JSON-serializable shapes but don't structurally satisfy
      // supabase-js's generated Json index signature.
      number_line: (ex.numberLine as unknown as Database["public"]["Tables"]["exercises"]["Insert"]["number_line"]) ?? null,
      tiles: (ex.tiles as unknown as Database["public"]["Tables"]["exercises"]["Insert"]["tiles"]) ?? null,
      grouping: (ex.grouping as unknown as Database["public"]["Tables"]["exercises"]["Insert"]["grouping"]) ?? null,
      correct_answer: ex.correctAnswer,
      computation: (ex.computation as unknown as Database["public"]["Tables"]["exercises"]["Insert"]["computation"]) ?? null,
      difficulty: ex.difficulty ?? null,
    }));
    for (let i = 0; i < rows.length; i += 200) {
      const { error } = await supabase.from("exercises").insert(rows.slice(i, i + 200));
      if (error) throw new Error(`Insert failed at batch starting ${i}: ${error.message}`);
    }
    console.log(`[seed] inserted ${rows.length} new exercises directly.`);
  } else {
    writeFileSync(OUT_PATH, JSON.stringify(allNew, null, 1));
    console.log(`[seed] wrote ${allNew.length} new exercises to ${OUT_PATH} for external insertion.`);
  }

  console.log("\n[seed] per-slot summary:");
  console.table(perSlotResult);
  const totalAfter = perSlotResult.reduce((s, r) => s + r.after, 0);
  const fullSlots = perSlotResult.filter((r) => r.after >= TARGET_PER_SLOT).length;
  console.log(`[seed] total banked (this run's view): ${totalAfter} across ${perSlotResult.length} slots; ${fullSlots}/${perSlotResult.length} at target.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
